changed word Tokenizer
soumendrak/openodia pull request #5
Opened 2021-09-29 07:51 UTC by JanviRaina

I made changes in the function and ran it separately and it is working fine. Let me know if this helps.

2021-09-29 17:56 UTC, soumendrak requested changes
@JanviRaina 
Thanks for the changes. I really appreciate it.
Could you please make the changes requested?
Also, can you please make sure the test cases are passing? Thank you.

2021-09-29 17:56 UTC, soumendrak commented on openodia/_understandData.py
> +# print(word_tokenizer(test_data))
Commented code should not be present in the code.
If past code is needed, can be fetched from `git` commit history.
Keeping commented code reduces readability factor.

2021-09-29 17:56 UTC, soumendrak commented on openodia/_understandData.py
> +        x=punct.split(test_data)
`test_data` should be `text`

2021-09-29 17:56 UTC, soumendrak commented on openodia/_understandData.py
> +        x=punct.split(test_data)
Please give the proper variable name depending on what it is and not `x`, `str1` and `i`

2021-09-29 17:56 UTC, soumendrak commented on openodia/_understandData.py
> +            str1+=i+' '
This `for` loop increases additional time complexity to the codebase. 
Is there any better way to do it?

2021-09-30 05:41 UTC, JanviRaina commented
I have removed the commented portion and replaced the for loop with 'join', have tried to give some better names to the variables.
Thanks for these suggestions.
I am not sure how to test this for all the test cases though. I have only tested it using print statement for this string
("ଭାରତୀୟ ସର୍ବୋଚ୍ଚ ନ୍ୟାୟାଳୟ, ଭାରତର ଉଚ୍ଚତମ ନ୍ୟାୟିକ ଅନୁଷ୍ଠାନ ଅଟେ ।") for which it seemed to have worked fine.

2021-10-04 19:26 UTC, soumendrak commented
@JanviRaina run
```shell
black openodia -l 99 -t py39
```
on command prompt to get rid of the linting issue.

2021-12-12 01:50 UTC, closed without merging